version: '3.8'
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: batysmonitor-db
    environment:
      POSTGRES_DB: batysmonitor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: batysmonitor-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: batysmonitor

volumes:
  pgdata: